
import SQLConnection.SQLConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    static Connection conn = null;

    public AdminMenu() {
        initComponents();
        conn = SQLConnection.connect();
    }

    private void closeWindow() {
        try {
            if (conn != null) {
                conn.close();
            }
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Exception caught in closing Connection" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        Close1 = new javax.swing.JButton();
        ta1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        Close2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ADD = new javax.swing.JMenu();
        Package = new javax.swing.JMenuItem();
        Transport = new javax.swing.JMenuItem();
        Agent = new javax.swing.JMenuItem();
        Hotel_And_Flights = new javax.swing.JMenuItem();
        Travel_Incharge = new javax.swing.JMenuItem();
        Search_Agent = new javax.swing.JMenu();
        Search_Package = new javax.swing.JMenu();
        Search_Transport = new javax.swing.JMenu();
        Search_Travel_Package = new javax.swing.JMenu();
        Search_One = new javax.swing.JMenuItem();
        View_All = new javax.swing.JMenuItem();
        Log_Out = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("menu"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Close1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Close1.setText("Close");
        Close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(Close1);
        Close1.setBounds(679, 0, 110, 25);

        ta1.setEditable(false);
        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        ta1.setRows(5);
        jLayeredPane2.add(ta1);
        ta1.setBounds(0, 0, 800, 600);

        jLayeredPane1.add(jLayeredPane2);
        jLayeredPane2.setBounds(0, 0, 800, 600);

        Close2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Close2.setText("Close");
        Close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close2ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(Close2);
        Close2.setBounds(340, 490, 100, 25);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Incharge ID", "Incharge Name", "Mobile No.", "City", "Passenger Assigned"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLayeredPane3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 799, 623);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 600);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/tajmahal -ADMIN.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 500));
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NAKSHATRA  TRAVELS");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(50, 0, 620, 43);

        ADD.setText("Add");

        Package.setText("Package");
        Package.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PackageActionPerformed(evt);
            }
        });
        ADD.add(Package);

        Transport.setText("Transport");
        Transport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransportActionPerformed(evt);
            }
        });
        ADD.add(Transport);

        Agent.setText("Agent");
        Agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentActionPerformed(evt);
            }
        });
        ADD.add(Agent);

        Hotel_And_Flights.setText("Hotel and flights");
        Hotel_And_Flights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hotel_And_FlightsActionPerformed(evt);
            }
        });
        ADD.add(Hotel_And_Flights);

        Travel_Incharge.setText("Travel Incharge");
        Travel_Incharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Travel_InchargeActionPerformed(evt);
            }
        });
        ADD.add(Travel_Incharge);

        jMenuBar1.add(ADD);

        Search_Agent.setText("Search agent");
        Search_Agent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_AgentMouseClicked(evt);
            }
        });
        jMenuBar1.add(Search_Agent);

        Search_Package.setText("Search package");
        Search_Package.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_PackageMouseClicked(evt);
            }
        });
        jMenuBar1.add(Search_Package);

        Search_Transport.setText("Search Transport");
        Search_Transport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_TransportMouseClicked(evt);
            }
        });
        jMenuBar1.add(Search_Transport);

        Search_Travel_Package.setText("Search Travel Incharge");

        Search_One.setText("search one");
        Search_One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_OneActionPerformed(evt);
            }
        });
        Search_Travel_Package.add(Search_One);

        View_All.setText("View All");
        View_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_AllActionPerformed(evt);
            }
        });
        Search_Travel_Package.add(View_All);

        jMenuBar1.add(Search_Travel_Package);

        Log_Out.setText("Log Out");
        Log_Out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_OutMouseClicked(evt);
            }
        });
        jMenuBar1.add(Log_Out);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Log_OutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseClicked
        int a = JOptionPane.showConfirmDialog(this, "DO YOU WISH TO LOG-OUT?", "Log Out confirmation", 0, JOptionPane.PLAIN_MESSAGE);
        if (a == 0) {
            new Login().setVisible(true);
            closeWindow();
        }
    }//GEN-LAST:event_Log_OutMouseClicked

    private void PackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PackageActionPerformed
        new AddPackage().setVisible(true);
        closeWindow();
    }//GEN-LAST:event_PackageActionPerformed

    private void Search_AgentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_AgentMouseClicked
        new SearchAgent().setVisible(true);
        closeWindow();
    }//GEN-LAST:event_Search_AgentMouseClicked

    private void Search_PackageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_PackageMouseClicked
        new SearchPackage().setVisible(true);
        closeWindow();
    }//GEN-LAST:event_Search_PackageMouseClicked

    private void TransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransportActionPerformed
        new AddTransport().setVisible(true);
        closeWindow();
    }//GEN-LAST:event_TransportActionPerformed

    private void Search_TransportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_TransportMouseClicked
        new SearchTransport().setVisible(true);
        closeWindow();
    }//GEN-LAST:event_Search_TransportMouseClicked

    private void AgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentActionPerformed
        new AddAgent().setVisible(true);// TODO add your handling code here:
        closeWindow();
    }//GEN-LAST:event_AgentActionPerformed

    public void repeatDialog() {
        String inchargeid = JOptionPane.showInputDialog(rootPane, "Enter Incharge ID:-", "Get Detail...", -1);
        ta1.setText("");
        if (inchargeid == null) {
            int a = JOptionPane.showConfirmDialog(this, "Incharge ID IS COMPULSORY .DO YO WANT TO RETRY?", "", 0, JOptionPane.PLAIN_MESSAGE);
            if (a == 0) {
                repeatDialog();
            }
        }
        inchargeid.trim();
        if (!(inchargeid.equals(""))) {
            try {
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String query = "select * from travelincharge where inchargeid='" + inchargeid + "';";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.first()) {
                    rs.first();
                    jLayeredPane2.setVisible(true);
                    String inchargename = rs.getString("inchargename");
                    String inchargecontact = rs.getString("mobno");
                    String operationalcity = rs.getString("operationalcity");
                    int passno = rs.getInt("passno");
                    ta1.append("                        TRAVEL INCHARGE DETAIL " + "\n\n" + "TRAVEL INCHARGE NAME -:" + inchargename + "\n" + "TRAVEL INCHARGE ID -: " + inchargeid + "\n" + "INCHARGE MOBILE NO.-: " + inchargecontact + "\n" + "CITY INCHARGE IS ASSIGNED -: " + operationalcity + "\n" + "PASSENGER ASSIGNED -: " + passno);
                } else {
                    int a = JOptionPane.showConfirmDialog(this, "THIS ID DOES NOT EXIST . WILL YOU LIKE TO TRY AGAIN?", "", 0, JOptionPane.PLAIN_MESSAGE);
                    if (a == 0) {
                        repeatDialog();
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            int a = JOptionPane.showConfirmDialog(this, "Incharge ID IS COMPULSORY .DO YO WANT TO RETRY?", "", 0, JOptionPane.PLAIN_MESSAGE);
            if (a == 0) {
                repeatDialog();
            }

        }
    }
    private void Search_OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_OneActionPerformed
        repeatDialog();
    }//GEN-LAST:event_Search_OneActionPerformed

    private void View_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_AllActionPerformed
        jPanel1.setVisible(true);
        try {
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "select * from travelincharge";
            ResultSet rs = stmt.executeQuery(query);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rows = rs.getRow();
            int rows1 = model.getRowCount();
            for (int i = 1; i <= rows1; i++) {
                model.removeRow(0);
            }
            while (rs.next()) {
                String inchargename = rs.getString("inchargename");
                String phoneno = rs.getString("mobno");
                String operationalcity = rs.getString("operationalcity");
                String inchargeid = rs.getString("inchargeid");
                int passno = rs.getInt("passno");
                model.addRow(new Object[]{inchargeid, inchargename, phoneno, operationalcity, passno});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_View_AllActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLayeredPane2.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void Close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close1ActionPerformed
        jLayeredPane2.setVisible(false);
    }//GEN-LAST:event_Close1ActionPerformed

    private void Close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close2ActionPerformed
        jPanel1.setVisible(false);
    }//GEN-LAST:event_Close2ActionPerformed

    private void Hotel_And_FlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hotel_And_FlightsActionPerformed
        new AddFlightAndHotels().setVisible(true);
        closeWindow();
    }//GEN-LAST:event_Hotel_And_FlightsActionPerformed

    private void Travel_InchargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Travel_InchargeActionPerformed
        new AddIncharge().setVisible(true);
        closeWindow();
    }//GEN-LAST:event_Travel_InchargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ADD;
    private javax.swing.JMenuItem Agent;
    private javax.swing.JButton Close1;
    private javax.swing.JButton Close2;
    private javax.swing.JMenuItem Hotel_And_Flights;
    private javax.swing.JMenu Log_Out;
    private javax.swing.JMenuItem Package;
    private javax.swing.JMenu Search_Agent;
    private javax.swing.JMenuItem Search_One;
    private javax.swing.JMenu Search_Package;
    private javax.swing.JMenu Search_Transport;
    private javax.swing.JMenu Search_Travel_Package;
    private javax.swing.JMenuItem Transport;
    private javax.swing.JMenuItem Travel_Incharge;
    private javax.swing.JMenuItem View_All;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables

}
