
import SQLConnection.SQLConnection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ATHARVA
 */
public class AgentMenu extends javax.swing.JFrame {

    static Connection conn = null;

    /**
     * Creates new form Main_menu
     */
    public AgentMenu() {
        initComponents();
    }

    private void closeWindow() {
        try {
            if (conn != null) {
                conn.close();
            }
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Exception caught in closing Connection " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jb1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jb1.setBackground(new java.awt.Color(255, 255, 255));
        jb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb1.setForeground(new java.awt.Color(0, 51, 255));
        jb1.setText("close");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jb1);
        jb1.setBounds(570, 0, 80, 25);

        ta1.setColumns(20);
        ta1.setEditable(false);
        ta1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        ta1.setRows(30);
        ta1.setTabSize(100);
        ta1.setAutoscrolls(false);
        jScrollPane1.setViewportView(ta1);

        jLayeredPane2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 650, 850);

        jRadioButton1.setBorder(null);
        jRadioButton1.setEnabled(false);
        jRadioButton1.setOpaque(false);
        jRadioButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseMoved(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jRadioButton1);
        jRadioButton1.setBounds(80, 470, 13, 50);

        jRadioButton2.setEnabled(false);
        jRadioButton2.setOpaque(false);
        jRadioButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseMoved(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jRadioButton2);
        jRadioButton2.setBounds(130, 480, 21, 30);

        jRadioButton3.setEnabled(false);
        jRadioButton3.setOpaque(false);
        jRadioButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseMoved(evt);
            }
        });
        jLayeredPane2.add(jRadioButton3);
        jRadioButton3.setBounds(180, 480, 21, 30);

        jRadioButton4.setEnabled(false);
        jRadioButton4.setOpaque(false);
        jRadioButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseMoved(evt);
            }
        });
        jLayeredPane2.add(jRadioButton4);
        jRadioButton4.setBounds(230, 480, 21, 30);

        jRadioButton5.setEnabled(false);
        jRadioButton5.setOpaque(false);
        jRadioButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton5MouseMoved(evt);
            }
        });
        jLayeredPane2.add(jRadioButton5);
        jRadioButton5.setBounds(280, 480, 21, 30);

        jRadioButton6.setEnabled(false);
        jRadioButton6.setOpaque(false);
        jRadioButton6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton6MouseMoved(evt);
            }
        });
        jLayeredPane2.add(jRadioButton6);
        jRadioButton6.setBounds(330, 480, 21, 30);

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setEnabled(false);
        jRadioButton7.setOpaque(false);
        jRadioButton7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton7MouseMoved(evt);
            }
        });
        jLayeredPane2.add(jRadioButton7);
        jRadioButton7.setBounds(380, 480, 21, 30);

        jRadioButton8.setEnabled(false);
        jRadioButton8.setOpaque(false);
        jRadioButton8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton8MouseMoved(evt);
            }
        });
        jLayeredPane2.add(jRadioButton8);
        jRadioButton8.setBounds(430, 480, 21, 30);

        jRadioButton9.setEnabled(false);
        jRadioButton9.setOpaque(false);
        jRadioButton9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton9MouseMoved(evt);
            }
        });
        jLayeredPane2.add(jRadioButton9);
        jRadioButton9.setBounds(490, 480, 21, 30);

        jRadioButton10.setEnabled(false);
        jRadioButton10.setOpaque(false);
        jRadioButton10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton10MouseMoved(evt);
            }
        });
        jLayeredPane2.add(jRadioButton10);
        jRadioButton10.setBounds(550, 480, 21, 30);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel2.setText("NAKSHATRA   TRAVELS");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(150, -10, 290, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Om-Namah-Shivaya jabalpur.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(650, 550));
        jLayeredPane2.add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 550);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        jMenu1.setText("package selection");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("passenger details");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("update traveler detail");

        jMenuItem4.setText("tour cancel");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("log out");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void repeatDialog() {
        String tid = JOptionPane.showInputDialog(rootPane, "Enter Traveller ID:-", "Get Detail...", -1);
        ta1.setText("");
        if (tid == null) {
            return;
        }
        tid.trim();
        if (!(tid.equals(""))) {
            try {
                Connection conn = SQLConnection.connect();
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String query = "select * from passenger where passid='" + tid + "';";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.first()) {
                    rs.first();
                    jScrollPane1.setVisible(true);
                    jb1.setVisible(true);
                    String passid = rs.getString("passid");
                    String passname = rs.getString("passname");
                    String bplace = rs.getString("bplace");
                    String dplace = rs.getString("dplace");
                    String packid = rs.getString("packid");
                    String packname = rs.getString("packname");
                    String fdt = rs.getString("fdt");
                    String tdt = rs.getString("tdt");
                    String aadharno = rs.getString("aadharno");
                    String ppno = rs.getString("ppno");
                    String mship = rs.getString("mship");
                    String mno = rs.getString("mno");
                    String email = rs.getString("email");
                    String inid = rs.getString("inid");
                    double tc = rs.getDouble("tc");
                    rs.close();
                    String query1 = "select * from travelincharge where operationalcity ='" + dplace + "' order by passno";
                    ResultSet rs1 = stmt.executeQuery(query1);
                    rs1.first();
                    String inname = rs1.getString("inname");
                    String inmno = rs1.getString("mobno");
                    rs1.close();
                    ta1.append("                        PASSENGER DETAIL " + "\n\n" + "PASSENGER ID-: " + passid + "\n" + "PASSENGER NAME-: " + passname + "\n" + "BOARDING -: " + bplace + "\n" + "DESTINATION -: " + dplace + "\n" + "PACKAGE ID -:" + packid + "\n" + " PACKAGE NAME -: " + packname + "\n" + "FROM DATE -: " + fdt + "      TO DATE -: " + tdt + "\n" + "AADHAR NO. -: " + aadharno + "\n" + "PASSPORT NO. -: " + ppno + "\n" + "MEMBERSHIP GRADE -:" + mship + "\n" + "MOBILE NO. -:" + mno + "\n" + "EMAIL -: " + email + "\n" + "TRAVEL INCHARGE NAME -:" + inname + "\n" + "TRAVEL INCHARGE ID -: " + inid + "\n" + "INCHARGE MOBILE NO.-: " + inmno + "\n" + "TOTAL COST -: " + tc);
                } else {
                    int a = JOptionPane.showConfirmDialog(this, "THIS ID DOES NOT EXIST . WILL YOU LIKE TO TRY AGAIN?", "", 0, JOptionPane.PLAIN_MESSAGE);
                    if (a == 0) {
                        repeatDialog();
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            int a = JOptionPane.showConfirmDialog(this, "PASSENGER ID IS COMPULSORY .DO YO WANT TO RETRY?", "", 0, JOptionPane.PLAIN_MESSAGE);
            if (a == 0) {
                repeatDialog();
            }
        }
    }
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        repeatDialog();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void anotherRepeatDialog() {
        String tid = JOptionPane.showInputDialog(rootPane, "Enter Traveller ID:-", "TOUR CANCELLATION", -1);
        if (tid == null) {
            return;
        }
        tid.trim();
        if (!(tid.equals(""))) {
            try {
                Connection conn = SQLConnection.connect();
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String query = "select * from passenger where passid='" + tid + "';";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.first()) {
                    rs.first();
                    String inid = rs.getString("inid");
                    double tc = rs.getDouble("tc");
                    JOptionPane.showMessageDialog(this, "RETURN THE TOTAL COST OF PACKAGE " + tc);
                    String query1 = "delete from passenger where passid ='" + tid + "';";
                    stmt.executeUpdate(query1);
                    String query2 = "update travelincharge set passno=passno-1 where inid='" + inid + "'";
                    stmt.executeUpdate(query2);
                    JOptionPane.showMessageDialog(this, "THE TOUR HAS DEARLY CANCELLED. HAVE  A NICE DAY.");
                } else {
                    int a = JOptionPane.showConfirmDialog(this, "THIS ID DOES NOT EXIST . WILL YOU LIKE TO TRY AGAIN?", "", 0, JOptionPane.PLAIN_MESSAGE);
                    if (a == 0) {
                        anotherRepeatDialog();
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            int a = JOptionPane.showConfirmDialog(this, "PASSENGER ID IS COMPULSORY .DO YO WANT TO RETRY?", "", 0, JOptionPane.PLAIN_MESSAGE);
            if (a == 0) {
                anotherRepeatDialog();
            }
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jScrollPane1.setVisible(false);
        jb1.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        anotherRepeatDialog();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        jScrollPane1.setVisible(false);
        ta1.setText("");
        jb1.setVisible(false);
    }//GEN-LAST:event_jb1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        closeWindow();
        new PackageSelection().setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        int a = JOptionPane.showConfirmDialog(this, "DO YOU WISH TO LOG-OUT?", "Log Out confirmation", 0, JOptionPane.PLAIN_MESSAGE);
        if (a == 0) {
            closeWindow();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    private void waitnseconds(int n) {
        long now = System.currentTimeMillis();
        long then = now + (1000 * n);
        while (System.currentTimeMillis() <= then) {
        }
    }

    private void graphic() {
        int n = 1;
        while (n <= 10) {
            switch (n) {
                case 1:
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/Om-Namah-Shivaya jabalpur.jpg")));
                    break;
                case 2:
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/tajmahal.jpg")));
                    break;
                case 3:
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/Gwalior_1.jpg")));
                    break;
                case 4:
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/un16145335.jpg")));
                    break;
                case 5:
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/un16147253.jpg")));
                    break;
                case 6:
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/tour_img-678251-92.jpg")));
                    break;
                case 7:
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/hwv1-aerial.jpg")));
                    break;
                case 8:
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/Wat-Arun-Bangkok_704x385 - agent.jpg")));
                    break;
                case 9:
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/untitled.jpg")));
                    break;
                case 10:
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/tours-chateau_d_amboise-1112x630.jpg")));
                    break;
            }
            n++;
            waitnseconds(1);
        }
    }
    private void jRadioButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/Om-Namah-Shivaya jabalpur.jpg")));
    }//GEN-LAST:event_jRadioButton1MouseMoved

    private void jRadioButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/tajmahal.jpg")));
    }//GEN-LAST:event_jRadioButton2MouseMoved

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/Gwalior_1.jpg")));
    }//GEN-LAST:event_jRadioButton3MouseMoved

    private void jRadioButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/un16145335.jpg")));
    }//GEN-LAST:event_jRadioButton4MouseMoved

    private void jRadioButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/un16147253.jpg")));
    }//GEN-LAST:event_jRadioButton5MouseMoved

    private void jRadioButton6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton6MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/tour_img-678251-92.jpg")));
    }//GEN-LAST:event_jRadioButton6MouseMoved

    private void jRadioButton7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton7MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/hwv1-aerial.jpg")));
    }//GEN-LAST:event_jRadioButton7MouseMoved

    private void jRadioButton9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton9MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/untitled.jpg")));
    }//GEN-LAST:event_jRadioButton9MouseMoved

    private void jRadioButton8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton8MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/Wat-Arun-Bangkok_704x385 - agent.jpg")));
    }//GEN-LAST:event_jRadioButton8MouseMoved

    private void jRadioButton10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton10MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMAGES/tours-chateau_d_amboise-1112x630.jpg")));
    }//GEN-LAST:event_jRadioButton10MouseMoved

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb1;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
