
import SQLConnection.SQLConnection;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * FinalReport.java
 *
 * Created on 28 Jan, 2018, 5:22:59 PM
 */
/**
 *
 * @author ATHARVA
 */
public class FinalReport extends javax.swing.JFrame {

    String pid, passid;
    double p;

    /**
     * Creates new form Final_report
     */
    public FinalReport() {
        initComponents();
    }

    public FinalReport(double cp, String cpid, String cpassid) {
        initComponents();
        pid = cpid;
        passid = cpassid;
        p = cp;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("FINAL REPORT");

        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("MS Gothic", 1, 16)); // NOI18N
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        jButton1.setText("PRINT REPORT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT TO AGENTMENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton1)
                        .addGap(123, 123, 123)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Connection conn = SQLConnection.connect();
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "select * from passenger where passid='" + passid + "';";
            ResultSet rs = stmt.executeQuery(query);
            rs.first();
            String passname = rs.getString("passname");
            String bplace = rs.getString("bplace");
            String dplace = rs.getString("dplace");
            String pkgid = rs.getString("pkgid");
            String pkgname = rs.getString("pkgname");
            String fdt = rs.getString("fdt");
            String tdt = rs.getString("tdt");
            String aadharno = rs.getString("aadharno");
            String ppno = rs.getString("ppno");
            String mship = rs.getString("mship");
            String mno = rs.getString("mno");
            String email = rs.getString("email");
            int nop = rs.getInt("nop");
            rs.close();
            String query1 = "select * from package where pid='" + pid + "'";
            ResultSet rs1 = stmt.executeQuery(query1);
            rs1.first();
            double d = 0.00;
            int price = rs1.getInt("price_perp");
            rs1.close();
            if (mship.equals("PLATINUM")) {
                d = 25.00;
            } else if (mship.equals("GOLD")) {
                d = 15.00;
            } else if (mship.equals("SILVER")) {
                d = 10.00;
            } else {
                d = 5.00;
            }
            long total = price * nop;
            double dis = (price * nop * d) / 100;
            double total1 = price * nop - dis;
            String query2 = "update passenger set tc=" + total1 + " where passid='" + passid + "'";
            stmt.executeUpdate(query2);
            double b = total1 * p * 0.01;
            String query3 = "select * from tincharge where city ='" + dplace + "' order by passno";
            ResultSet rs2 = stmt.executeQuery(query3);
            rs2.first();
            String inid = rs2.getString("inid");
            String inname = rs2.getString("inname");
            String inmno = rs2.getString("mobno");
            rs2.close();
            String query4 = "update tincharge set passno=passno+1 where inname ='" + inname + "'";
            String query5 = "update passenger set inid='" + inid + " 'where passid='" + passid + "'";
            stmt.executeUpdate(query4);
            stmt.executeUpdate(query5);
            ta1.append("                        PASSENGER DETAIL " + "\n\n" + "PASSENGER ID-:" + passid + "\n" + "PASSENGER NAME-:" + passname + "\n" + "BOARDING -:" + bplace + "\n" + "DESTINATION -:" + dplace + "\n" + "PACKAGE ID -:" + pkgid + "\n" + "PACKAGE NAME -:" + pkgname + "\n" + "FROM DATE -:" + fdt + "      TO DATE -:" + tdt + "\n" + "AADHAR NO. -:" + aadharno + "\n" + "PASSPORT NO. -:" + ppno + "\n" + "MEMBERSHIP GRADE -:" + mship + "\n" + "MOBILE NO. -:" + mno + "\n" + "EMAIL -:" + email + "\n" + "NO. OF PEOPLE -:" + nop + "\n" + "PRICE PER PEOPLE -:" + price + "\n" + "TOTAL PRICE -: " + total + "\n" + "DISCOUNT DUE TO MEMBERSHIP-: " + dis + "\n" + "TOTAL PRICE AFTER DISCOUNT -: " + total1 + "\n" + "PRICE OF HOTEL AND FLIGHT-: " + b + "\n" + "TRAVEL INCHARGE NAME -:" + inname + "\n" + "TRAVEL INCHARGE ID -:" + inid + "\n" + "INCHARGE MOBILE NO.-:" + inmno);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new AgentMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ta1.print();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables

}
